version: '3.8'
services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6479:6379'
    command: redis-server --save 20 1
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local
